numbers = [20, 10 ,36, 26, 50, 3, 10]
friends = ["keerthi","navya","sruthi","pooji","shivani"]
print(numbers)
print(friends)
friends.extend(numbers)
print(friends)
friends.append("vyshu")
print(friends)
friends.pop()
print(friends)
friends.clear()
print(friends)
print(numbers.count(10))
print(numbers.index(10))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
friends2 = friends.copy()
print(friends2)